### PR TITLE
update to PyPi

### PR DESCRIPTION
**Pull request by Tungsteno74**

### CODE REVIEW

**Comment by hoechenberger** [comment]
1.6.0 is currently not listed on PyPI (only on GitHub in the release section of the project), are you going to upload it to PyPI too? :)

**Comment by Tungsteno74** [comment]
Hello @hoechenberger , i updated it on pypi just now. It took me a while because I had some problems with uploading on the new pypi server through the automatic build service on SemaporeCI. Now it's all ok, check for 1.6.0 and have fun.
If you like to contribute more on this project and you have an account on PyPi i can put you as a mantainer of this project. Contact me if you like the idea ;)

**Comment by hoechenberger** [comment]
Hi @Tungsteno74, thank you very much! I don't know _how much_ I can actually help, but for example I would like to build & publish a Py 3.6 wheel. If you make me a co-maintainer, I could actually do this myself :) My PyPI username is `hoechenberger`.

Btw I created a `conda-forge` package about 2 weeks back, if _you_ would like to become a co-maintainer of the recipe, let me know ;)
https://anaconda.org/conda-forge/pyWinhook

**Comment by Tungsteno74** [comment]
@hoechenberger  i added you as Collaborator on Github (so you can push a new version on the PyPi-CI branch) and as mantainer on the PyPi archive. 
At this point, if you get a SemaphoreCI accout i will add you on it too.
Unfortunately, I have to decline your request as conda-forge co-mantainer, because i haven't an account on it.

Cheers

**Comment by hoechenberger** [comment]
Thank you @Tungsteno74!

> At this point, if you get a SemaphoreCI accout i will add you on it too.

I'm `hoechenberger` on SemaphoreCI.

> Unfortunately, I have to decline your request as conda-forge co-mantainer, because i haven't an account on it.

Heh, you don't need any special account :) To maintain the recipe "feedstock" all that's needed is a GitHub account, this will then give you push access to https://github.com/conda-forge/pywinhook-feedstock

**Comment by hoechenberger** [comment]
I just uploaded a Python 3.6 wheel to PyPI (and added the other binary distributions for Py3.6 to the GitHub release)

**Comment by Tungsteno74** [comment]
> I'm `hoechenberger` on SemaphoreCI.

Well, added here too !

> Heh, you don't need any special account :) To maintain the recipe "feedstock" all that's needed is a GitHub account, this will then give you push access to https://github.com/conda-forge/pywinhook-feedstock

I think i will never use it (as I've never used it so far), anyhow, thanks for having proposed it to me. I appreciate it. 

> I just uploaded a Python 3.6 wheel to PyPI (and added the other binary distributions for Py3.6 to the GitHub release)

Well done :)

**Pull request merged**
